""" 
This `Snakefile` runs the full analysis of the transmission bottleneck 
of SARS-CoV-2 from a fishing boat cohort.

Author: Will Hannon – https://www.linkedin.com/in/williamhannon/
"""

#### ----------------------- Imports ----------------------- ####

import pandas as pd 
import numpy as np
from os.path import join
from snakemake.utils import min_version

min_version('5.6.0')  # require `snakemake` >= 5.6.0

#### -------------------- Configuration -------------------- ####

configfile: "config/config.yml"

#### ------------------------ Utils ------------------------ ####

include: "rules/common.smk"

#### ----------------------- Targets ----------------------- ####
localrules: all, fastqc_raw, fastqc_trim, trim_adapters_se

rule all:
    input: 
        join(config['pileup_dir'], "pysam-variants.csv"),
        get_fastqc_runs()
          
        
rule clean:
    shell:
        """
        rm -rf logs/
        rm -rf tmp/
        rm -f slurm*.out
        """
#### ------------------------ Rules ------------------------ ####

include: "rules/qc-tools.smk"
include: "rules/download-reference.smk"
include: "rules/download-fastq.smk"
include: "rules/index-reference.smk"
include: "rules/trim-adapters.smk"
include: "rules/filter-reads.smk"
include: "rules/align-reads.smk"
include: "rules/calculate-coverage.smk"
include: "rules/calculate-pileup.smk"


