""" 
This Snakemake file runs the template analysis for the viral-deepseq pipeline.

Author: Will Hannon – https://www.linkedin.com/in/williamhannon/
"""

#### ----------------------- Imports ----------------------- ####

import pandas as pd 
from os.path import join
from snakemake.utils import min_version

min_version('5.6.0')  # require `snakemake` >= 5.6.0

#### -------------------- Configuration -------------------- ####

configfile: "config/config.yml"

#### ------------------------ Utils ------------------------ ####

include: "rules/common.smk"

#### ----------------------- Targets ----------------------- ####

rule all:
    input: 
        join(config['variant_dir'], "variants.csv"),
        join(config['pileup_dir'], "raw-variants.csv"),
        join(config['qc_dir'], 'multiqc'),
        join(config['split_dir'], "merged.bedgraph"),
        expand(join(config['pileup_dir'], "{aligner}", "{accession}", "{accession}.{aligner}.will.mpileup.csv"), accession=pd.read_csv(config['samples']['file'])['Run'], aligner=['BWA'])

rule clean:
    shell:
        """
        rm -rf logs/
        rm -rf tmp/
        rm -f slurm*.out
        """
#### ------------------------ Rules ------------------------ ####

include: "rules/reference.smk"
include: "rules/index-reference.smk"
include: "rules/fastq-download.smk"

include: "rules/tools.smk"
include: "rules/sra.smk"
include: "rules/qc.smk"
include: "rules/trim.smk"
include: "rules/align.smk"
include: "rules/variant.smk"
include: "rules/pileup.smk"
