""" 
This `Snakefile` runs the full analysis of the transmission bottleneck 
of SARS-CoV-2 from a fishing boat cohort.

Author: Will Hannon – https://www.linkedin.com/in/williamhannon/
"""

#### ----------------------- Imports ----------------------- ####

import pandas as pd 
import numpy as np
from os.path import join
from snakemake.utils import min_version

min_version('5.6.0')  # require `snakemake` >= 5.6.0

#### -------------------- Configuration -------------------- ####

configfile: "config/config.yml"

#### ------------------------ Utils ------------------------ ####

include: "rules/common.smk"

#### ----------------------- Targets ----------------------- ####
samples = list(set(pd.read_csv(config['samples']['file'])['Run']))

rule all:
    input: 
        join(config['pileup_dir'], "pysam-variants.csv"),
        join(config['variant_dir'], "variants.csv"),
        join(config['qc_dir'], 'formatted_multiqc_data.csv'),  
        join(config['qc_dir'], "BBduk_filtered_reads.csv"),
        join(config['coverage_dir'], "coverage.stats"),
        join(config['coverage_dir'], "merged.average.depth"),
        join(config['coverage_dir'], "merged.depth"),
        join(config['consensus_dir'], "aligned_consensus.fa"),
        join(config['consensus_dir'], "aligned_consensus.fa.iqtree"),
        join(config['phylogeny_dir'], "custom-boat-sequences.png"),
        join(config['phylogeny_dir'], "all-boat-sequences.png"),
        join(config['phylogeny_dir'], "representative-global-phylogeny.png"),
        join(config['phylogeny_dir'], "washington-only-phylogeny.png")


rule clean:
    shell:
        """
        rm -rf logs/
        rm -rf tmp/
        rm -f slurm*.out
        """
#### ------------------------ Rules ------------------------ ####

include: "rules/qc-tools.smk"
include: "rules/download-reference.smk"
include: "rules/download-tools.smk"
include: "rules/download-fastq.smk"
include: "rules/index-reference.smk"
include: "rules/trim-adapters.smk"
include: "rules/filter-reads.smk"
include: "rules/align-reads.smk"
include: "rules/calculate-coverage.smk"
include: "rules/calculate-pileup.smk"
include: "rules/call-variants.smk"
include: "rules/call-consensus.smk"
include: "rules/build-phylogeny.smk"
