#### ============ viral-deepseq configuration file ============ ####
#                                                                  #
# This file contains the tunable parameters for the viral-deepseq  #
# pipeline.                                                        #
#                                                                  #
#### -------------------------- Util -------------------------- ####

varscan: https://github.com/dkoboldt/varscan/raw/master/VarScan.v2.4.0.jar
snpeff: http://sourceforge.net/projects/snpeff/files/snpEff_latest_core.zip

#### ------------------------- Samples ------------------------ ####

samples: 
  file: config/samples.csv
  public: TRUE

#### ------------------------ Genomes ----------------------- ####
# Put viral and host genome ftp download locations here.         #
# organism:                                                      #
#   reference sequence: ftp://                                   #
#   gff annotations: ftp://                                      #
#   contig: `only if the sequence is viral give it's contig`     #
#### -------------------------------------------------------- ####

SARS2:
  ref: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/858/895/GCF_009858895.2_ASM985889v3/GCF_009858895.2_ASM985889v3_genomic.fna.gz
  gff: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/858/895/GCF_009858895.2_ASM985889v3/GCF_009858895.2_ASM985889v3_genomic.gff.gz
  contig: NC_045512.2

human:
  ref: ftp://ftp.ensembl.org/pub/release-99/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
  gtf: ftp://ftp.ensembl.org/pub/release-99/gtf/homo_sapiens/Homo_sapiens.GRCh38.99.gtf.gz

#### ------------------------ Params ----------------------- ####

# Desired thread count for each rule
threads:
  max_cpu: 32
  fastq_download: 8
  pileup: 16

# Remove duplicates with Picard
remove_duplicates: false

# Average base quality score to exclude below
BQ: 25

# Bin size for coverage graphs
bin_size: 50

# Parameters for variant calling.
min_coverage: 100
min_reads_supporting: 10
min_allele_frequency: 0.005
strand_bias_filter: 1
maxdepth: 100000

# Kmer lengths for consensus assembly - tune to read length
kmer:
    error_correct: 24
    extend_reads: 31
    assemble_contigs: 50

#### ------------------------- Dirs ------------------------ ####

# ++ Results Directoties ++ #
fastq_dir: results/fastq
trim_dir: results/trimmed
filter_dir: results/filtered
align_dir: results/aligned
qc_dir: results/qc
coverage_dir: results/coverage
variant_dir: results/variants
pileup_dir: results/pileup
consensus_dir: results/consensus

# ++ Config Directoties ++ #
tools: config/tools
ref_dir: config/ref
gff_dir: config/gff
gisaid_dir: config/gisaid
index_dir: 
  bwa: config/index/bwa
  star: config/index/star
  samtools: config/index/samtools
